#cloud-config
autoinstall:
  version: 1
  interactive-sections: []
  identity:
    hostname: patrimonio-desktop
    username: admlocal
    password: '$y$j9T$TH8Uffo23x//VhuiereEP/$W02uXVLFdleOsnKD9tNNLmZx0kqAymUoHyxsedPBjTD'
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  timezone: "America/Recife"
  storage:
    wipe: superblock-recursive  # Garante que todas as partições sejam apagadas antes de criar novas
    layout:
      name: custom
    config:
      - id: disk0
        type: disk
        match: sda
        ptable: gpt
        wipe: superblock  # Força a formatação completa do disco
        preserve: false  # Garante que as partições antigas não sejam preservadas
        partitions:
          - id: part1
            type: partition
            number: 1
            size: 1G
            flag: boot
            fstype: fat32
            preserve: false
            grub_device: true
            mountpoint: /boot/efi
          - id: part2
            type: partition
            number: 2
            size: 20G
            wipe: superblock
            fstype: ext4
            preserve: false
            mountpoint: /
          - id: part3
            type: partition
            number: 3
            size: 4G
            wipe: superblock
            fstype: swap
            preserve: false
          - id: part4
            type: partition
            number: 4
            size: -1
            wipe: superblock
            fstype: ext4
            preserve: false
            mountpoint: /home
  updates: all
  power_state:
    mode: reboot
    message: "Reiniciando após a instalação..."
    timeout: 30
    condition: always
