#cloud-config
autoinstall:
  version: 1
  interactive-sections: []
  identity:
    hostname: patrimonio-desktop
    username: admlocal
    password: '$y$j9T$TH8Uffo23x//VhuiereEP/$W02uXVLFdleOsnKD9tNNLmZx0kqAymUoHyxsedPBjTD'
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  timezone: "America/Recife"
  storage:
    wipe: true
    layout:
      name: custom
    config:
      - id: disk0
        type: disk
        match: sda  # Especificando diretamente para evitar problemas com "largest"
        ptable: gpt
        wipe: superblock-recursive
        partitions:
          - type: partition
            size: 1G
            flag: boot
            fstype: fat32
            mountpoint: /boot/efi
          - type: partition
            size: 20G
            wipe: superblock-recursive
            fstype: ext4
            mountpoint: /
          - type: partition
            size: 4G
            wipe: superblock-recursive
            fstype: swap
          - type: partition
            size: -1
            wipe: superblock-recursive
            fstype: ext4
            mountpoint: /home
  updates: all
  power_state:
    mode: reboot
    message: "Reiniciando após a instalação..."
    timeout: 30
    condition: always
