#cloud-config
autoinstall:
  version: 1
  identity:
      hostname: patrimonio-desktop
      username: admlocal
      password: '$y$j9T$KMJgqOBdDSxdh/qddcR37/$WX6BW.IhOOVNzbo6F1M2Q3EmjSQirA.TlqotGW.AlJ2'
      groups: sudo
  locale: pt_BR.UTF-8
  keyboard:
      layout: br
  timezone: "America/Recife"
  updates: all
  shutdown: reboot
  storage:
      layout:
          name: custom
      config:
          - id: disk0
            type: disk
            match: largest  # Auto detecta o maior disco disponível
            ptable: gpt
            wipe: superblock-recursive
            partitions:
                - size: 1G
                  flag: boot
                  grub_device: true
                  fstype: fat32
                  mountpoint: /boot
                - size: 60G
                  wipe: superblock-recursive
                  fstype: ext4
                  mountpoint: /
                - size: -1
                  wipe: superblock-recursive
                  fstype: ext4
                  mountpoint: /home
  
