#cloud-config
autoinstall:
  version: 1
  schema: autoinstall-v1  # Garante compatibilidade com o instalador
  identity:
    hostname: patrimonio-desktop
    username: admlocal
    password: '$y$j9T$TH8Uffo23x//VhuiereEP/$W02uXVLFdleOsnKD9tNNLmZx0kqAymUoHyxsedPBjTD'
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  timezone: "America/Recife"
  storage:
    wipe: true
    layout:
      name: custom
    config:
      - id: disk0
        type: disk
        match: largest  
        ptable: gpt
        wipe: superblock-recursive
        partitions:
          - size: 1G
            flag: boot
            grub_device: true
            fstype: fat32
            mountpoint: /boot/efi
          - size: 40G
            wipe: superblock-recursive
            fstype: ext4
            mountpoint: /
          - size: 4G
            wipe: superblock-recursive
            fstype: swap
          - size: -1
            wipe: superblock-recursive
            fstype: ext4
            mountpoint: /home
  updates: all
  power_state:
    mode: reboot
    message: "Reiniciando após a instalação..."
    timeout: 30
    condition: always
