#cloud-config
autoinstall:
  version: 1
  interactive-sections: []
  identity:
    hostname: patrimonio-desktop
    username: admlocal
    password: '$y$j9T$TH8Uffo23x//VhuiereEP/$W02uXVLFdleOsnKD9tNNLmZx0kqAymUoHyxsedPBjTD'
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  timezone: "America/Recife"
  storage:
    reset-partitions: true  # Apaga todas as partições antes da instalação
    wipe: superblock-recursive
    layout:
      name: raw  # Alterado de 'custom' para 'raw' para garantir que o instalador não aplique um particionamento automático
    config:
      - id: disk0
        type: disk
        match: largest  # Detecta automaticamente o maior disco disponível
        ptable: gpt  # Se a VM estiver em modo Legacy (BIOS), troque para "mbr"
        wipe: superblock-recursive
        overwrite: true  # Garante que qualquer esquema de partição existente seja apagado antes da instalação
        partitions:
          - type: partition
            size: 1G
            flag: boot
            fstype: fat32
            mountpoint: /boot/efi
          - type: partition
            size: 50G
            fstype: ext4
            mountpoint: /
          - type: partition
            size: 8G
            fstype: swap
          - type: partition
            size: -1
            fstype: ext4
            mountpoint: /home
  updates: all
  power_state:
    mode: reboot
    message: "Reiniciando após a instalação..."
    timeout: 30
    condition: always
