#cloud-config
autoinstall:
  version: 1
  schema: autoinstall-v1
  interactive-sections: []
  identity:
    hostname: patrimonio-desktop
    username: admlocal
    password: '$y$j9T$TH8Uffo23x//VhuiereEP/$W02uXVLFdleOsnKD9tNNLmZx0kqAymUoHyxsedPBjTD'
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  timezone: "America/Recife"

  # Configuração de armazenamento (particionamento com LVM)
  storage: 
    layout:
      name: lvm  # Usamos LVM para particionamento.
      sizing-policy: all  # Usa o disco inteiro.
      match:
        size: largest  # O maior disco será escolhido automaticamente.

    # Configuração das partições
    config:
      # Partição UEFI (FAT32) - Necessário para sistemas UEFI
      - type: partition
        id: uefi
        device: disk0  # Ajuste o nome do dispositivo, como /dev/sda ou /dev/nvme0n1
        size: 1.13GB  # Tamanho para a partição EFI
        flag: boot
        format: fat32
        mountpoint: /boot/efi  # Mount point para a partição UEFI

      # Partição Swap (LVM)
      - type: partition
        id: swap
        device: disk0
        size: 4GB
        format: swap
        mountpoint: none  # Swap não precisa de mount point, mas é necessário incluí-lo

      # Partição Root (/) - Usando LVM
      - type: partition
        id: root
        device: disk0
        size: 50GB
        format: ext4
        mountpoint: /  # Mount point para a partição raiz (root)

      # Partição Home (restante do espaço) - Usando LVM
      - type: partition
        id: home
        device: disk0
        size: remaining  # O restante do espaço disponível
        format: ext4
        mountpoint: /home  # Mount point para a partição home

  # Configuração do estado de energia após a instalação (reiniciar)
  power_state:
    mode: reboot
    message: "Reiniciando após a instalação..."
    timeout: 30
    condition: always
